// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace SurvivalGameplayTags
{
	SURVIVALPROJECT_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all the custom native tags that project will use
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
					   	
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
					   	
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SecondInteract);
					   	
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
					   	
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);
					   	
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);
					   	
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Sprinting);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	
	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	SURVIVALPROJECT_API		extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	SURVIVALPROJECT_API		extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	
	SURVIVALPROJECT_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
}
